force-app/main/default/objects/Language__c/Language__c.object-meta.xml
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Language__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <formula>Name + &#39;_&#39; + TEXT(Topics_Count__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <formula>Name + &#39;_&#39; + TEXT(Project_Topics_Count__c)  + &#39;_&#39; + TEXT(Project_Topics_Selected_Count__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Topic__c/Project_Topic__c.object-meta.xml
<CustomObject>
    <label>Project Topic</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Project Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Topic__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Topics</relationshipLabel>
    <relationshipName>Project_Topics</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Topic__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Project Topics</relationshipLabel>
    <relationshipName>Project_Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <displayFormat>TOPIC-{0000}</displayFormat>
        <label>Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Topic__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <formula>Title__c + &#39;_&#39; +  TEXT(Project_Topics_Count__c)  + &#39;_&#39; + TEXT(Project_Topics_Selected_Count__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Topic__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <referenceTo>Language__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssetController.cls
public with sharing class AssetController {
	@AuraEnabled(cacheable=true)
	public static List<Language__c> getLanguages(String searchLanguage) {
		String searchLanguageLike = '%' + searchLanguage + '%';
		List<Language__c> languages = [SELECT Id, Name, Label__c FROM Language__c WHERE Name LIKE :searchLanguageLike ORDER BY LastModifiedDate DESC];
		return languages;
	}

	@AuraEnabled(cacheable=true)
	public static List<Topic__c> getTopics(List<String> languageIdList, String searchTitle) {
		String searchTitleLike = '%' + searchTitle + '%';
		List<Topic__c> topics = [SELECT Id, Name,  Label__c , Title__c, Description__c FROM Topic__c  WHERE Language__c IN: languageIdList AND Title__c LIKE :searchTitleLike ORDER BY LastModifiedDate DESC];
		return topics;
	}

	@AuraEnabled(cacheable=true)
	public static List<Topic__c> getTopicsByLanguageId(String languageId, String searchTitle) {
		String searchTitleLike = '%' + searchTitle + '%';
		List<Topic__c> topics = [SELECT Id, Name, Label__c, Title__c FROM Topic__c  WHERE Language__c =: languageId AND Title__c LIKE :searchTitleLike ORDER BY LastModifiedDate DESC];
		return topics;
	}

	@AuraEnabled(cacheable=true)
	public static List<Project__c> getProjects(String searchProject) {
		String searchProjectLike = '%' + searchProject + '%';
		List<Project__c> projects = [SELECT Id, Name, Label__c FROM Project__c WHERE Name LIKE :searchProjectLike ORDER BY LastModifiedDate DESC];
		return projects;
	}

	@AuraEnabled(cacheable=true)
	public static Map<Id, Project_Topic__c> getProjectTopicsByProjectId(String projectId,String searchProjectTopic) {
		String searchProjectTopicLike = '%' + searchProjectTopic + '%';
		Map<Id, Project_Topic__c> projectTopics = new Map<Id, Project_Topic__c>([SELECT Id, Name, Project__c, Topic__c, Selected__c, Topic__r.Title__c, Topic__r.Description__c, Topic__r.Label__c FROM Project_Topic__c  WHERE Project__c =: projectId AND Topic__r.Title__c LIKE :searchProjectTopicLike ORDER BY CreatedDate DESC]);
		return projectTopics;
	}

	@AuraEnabled(cacheable=true)
	public static List<Project_Topic__c> getProjectTopicsByProjectIdAndLanguageId(String projectId, String languageId) {
		List<Project_Topic__c> projectTopics = [SELECT Id, Topic__c FROM Project_Topic__c  WHERE Project__c =: projectId AND Topic__r.Language__c =: languageId ORDER BY Topic__r.LastModifiedDate DESC];
		return projectTopics;
	}

	@AuraEnabled(cacheable=true)
	public static List<Topic__c> getTopicsByLanguageIdNotInProject(String projectId, String languageId ,String searchTitle) {
		String searchTitleLike = '%' + searchTitle + '%';
		List<Topic__c> topics = [SELECT Id, Name, Title__c FROM Topic__c  WHERE Language__c =: languageId AND Title__c LIKE :searchTitleLike  AND Id NOT IN (SELECT Topic__c FROM Project_Topic__c WHERE Project__c =: projectId) ORDER BY LastModifiedDate DESC];
		return topics;
	}

	@AuraEnabled()
	public static List<Project_Topic__c> createProjectTopics(String projectId, List<String> topicIdList, Boolean insertRecords) {
		List<Project_Topic__c> projectTopicList =  new List<Project_Topic__c>();
		if(insertRecords)
		{
			for(String topicId  : topicIdList){
			projectTopicList.add(new Project_Topic__c(Project__c = projectId,
			Topic__c = topicId));
			}
			if(projectTopicList.size() > 0){
				insert projectTopicList;
			}
		}
		return projectTopicList;
	}
}